'use client'

import { useEffect, useRef, useState } from 'react'
import type { MaiState } from '../../lib/v2/state'
import type { SecondaryView } from './V2AreasBase'

type Row = Record<string, any>
type Commit = (change:(current:MaiState)=>MaiState)=>void
type Props={view:SecondaryView;state:MaiState;today:string;commit:Commit;googleRpc:(method:string,args?:unknown[])=>Promise<any>}
const rows=(value:unknown):Row[]=>Array.isArray(value)?value as Row[]:[]
const button={border:'1px solid var(--divider)',background:'var(--bg-card)',color:'var(--text-primary)',borderRadius:8,padding:'8px 10px',cursor:'pointer',font:'inherit'} as const
const input={border:'1px solid var(--divider)',background:'var(--bg-primary)',color:'var(--text-primary)',borderRadius:8,padding:'9px 10px',width:'100%',font:'inherit'} as const
const card={border:'1px solid var(--divider)',background:'var(--bg-primary)',borderRadius:12,padding:12} as const
const overlay={position:'fixed',inset:0,zIndex:10300,background:'rgba(20,22,20,.52)',display:'grid',placeItems:'center',padding:16} as const
const sheet={width:'min(880px,96vw)',maxHeight:'90vh',overflow:'auto',background:'var(--bg-card)',color:'var(--text-primary)',border:'1px solid var(--divider)',borderRadius:18,padding:20,boxShadow:'0 28px 80px rgba(0,0,0,.3)'} as const
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const icons=['star','favorite','fitness_center','local_drink','menu_book','self_improvement','directions_run','bedtime','palette','code','attach_money','psychology','restaurant','cleaning_services','directions_bike','air','spa','bolt','school','monitor_heart']
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(String(r.result||''));r.readAsDataURL(file)})}

function Rich({value,onChange}:{value:string;onChange:(value:string)=>void}){
  const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(ref.current&&ref.current.innerHTML!==value)ref.current.innerHTML=value},[value]);
  const cmd=(name:string,arg?:string)=>{ref.current?.focus();document.execCommand(name,false,arg);onChange(ref.current?.innerHTML||'')}
  return <><div style={{display:'flex',gap:5,flexWrap:'wrap',marginBottom:6}}><button style={button} type="button" onClick={()=>cmd('bold')}><b>B</b></button><button style={button} type="button" onClick={()=>cmd('italic')}><i>I</i></button><button style={button} type="button" onClick={()=>cmd('underline')}><u>U</u></button><button style={button} type="button" onClick={()=>cmd('strikeThrough')}><s>S</s></button><button style={button} type="button" onClick={()=>cmd('insertUnorderedList')}>• Lista</button><button style={button} type="button" onClick={()=>cmd('insertOrderedList')}>1. Lista</button><button style={button} type="button" onClick={()=>{const url=prompt('Link:');if(url)cmd('createLink',url)}}>Link</button></div><div ref={ref} contentEditable suppressContentEditableWarning onInput={e=>onChange(e.currentTarget.innerHTML)} style={{...input,minHeight:150,lineHeight:1.55,overflow:'auto'}}/></>
}

function HabitDetails({state,commit}:{state:MaiState;commit:Commit}){
 const habits=rows(state.habits).filter(h=>h.ativo!==false);const [selected,setSelected]=useState(String(habits[0]?.id||''));const habit=habits.find(h=>String(h.id)===selected)||habits[0]
 if(!habit)return <p>Nenhuma rotina cadastrada.</p>
 function setIcon(icon:string){commit(current=>({...current,habits:rows(current.habits).map(h=>String(h.id)===String(habit.id)?{...h,icone:icon}:h)}))}
 return <div style={{display:'grid',gap:12}}><select style={input} value={String(habit.id)} onChange={e=>setSelected(e.target.value)}>{habits.map(h=><option key={String(h.id)} value={h.id}>{h.nome}</option>)}</select><section style={card}><strong>Paleta completa de ícones do original</strong><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:7,marginTop:10}}>{icons.map(icon=><button key={icon} style={{...button,background:habit.icone===icon?'var(--bg-hover)':'var(--bg-card)',minHeight:52}} onClick={()=>setIcon(icon)}><span className="material-symbols-rounded" style={{fontSize:22}}>{icon}</span><small style={{display:'block',fontSize:8,opacity:.55}}>{icon}</small></button>)}</div></section></div>
}

function GoalDetails({state,commit,googleRpc}:{state:MaiState;commit:Commit;googleRpc:Props['googleRpc']}){
 const goals=rows(state.goals);const [selected,setSelected]=useState(String(goals[0]?.id||''));const goal=goals.find(g=>String(g.id)===selected)||goals[0];const [html,setHtml]=useState(String(goal?.descricao||''));const [attachments,setAttachments]=useState<Row[]>(rows(goal?.anexos));const [busy,setBusy]=useState(false)
 useEffect(()=>{setHtml(String(goal?.descricao||''));setAttachments(rows(goal?.anexos))},[selected,goal?.id])
 if(!goal)return <p>Nenhuma meta cadastrada.</p>
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);try{const added:Row[]=[];for(const file of Array.from(files)){const data=await fileData(file);const result=await googleRpc('salvarAnexoDrive',[data,file.name,file.type]);const item=result?.item||result;added.push({idDrive:item.id,nome:item.name||item.nome||file.name,tipo:item.tipo||item.mimeType||file.type,url:item.url||item.webViewLink||'',directUrl:item.url||item.webViewLink||''})}setAttachments(v=>[...v,...added])}finally{setBusy(false)}}
 function insert(file:Row){const safe=String(file.nome||'arquivo').replaceAll('"','&quot;');setHtml(value=>value+(String(file.tipo||'').startsWith('image/')?`<p><img src="${file.directUrl||file.url}" alt="${safe}" /></p>`:`<p><a href="${file.url}" target="_blank">Anexo: ${safe}</a></p>`))}
 function save(){commit(current=>({...current,goals:rows(current.goals).map(g=>String(g.id)===String(goal.id)?{...g,descricao:html,anexos:attachments}:g)}));alert('Descrição e anexos da meta salvos.')}
 return <div style={{display:'grid',gap:12}}><select style={input} value={String(goal.id)} onChange={e=>setSelected(e.target.value)}>{goals.map(g=><option key={String(g.id)} value={g.id}>{g.titulo}</option>)}</select><section style={card}><strong>Descrição rica</strong><div style={{marginTop:8}}><Rich value={html} onChange={setHtml}/></div></section><section style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>Bandeja de anexos</strong><label style={button}>{busy?'Enviando…':'Adicionar vários'}<input hidden multiple type="file" disabled={busy} onChange={e=>void upload(e.target.files)}/></label></div><div style={{display:'grid',gap:6,marginTop:8}}>{attachments.map((file,index)=><div key={`${file.idDrive}-${index}`} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8}}><a href={file.url||'#'} target="_blank" rel="noreferrer" style={{color:'inherit'}}>{file.nome}</a><span style={{display:'flex',gap:5}}><button style={button} onClick={()=>insert(file)}>Inserir no texto</button><button style={button} onClick={()=>setAttachments(v=>v.filter((_,i)=>i!==index))}>×</button></span></div>)}</div></section><button style={{...button,justifySelf:'end'}} onClick={save}>Salvar alterações</button></div>
}

function NoteDetails({state,commit}:{state:MaiState;commit:Commit}){
 const notes=rows(state.notes).filter(n=>n.ativo!==false);const [selected,setSelected]=useState(String(notes[0]?.id||''));const note=notes.find(n=>String(n.id)===selected)||notes[0]
 if(!note)return <p>Nenhuma nota ativa.</p>
 function size(value:string){commit(current=>({...current,notes:rows(current.notes).map(n=>String(n.id)===String(note.id)?{...n,tamanho:value}:n)}))}
 return <div style={{display:'grid',gap:12}}><select style={input} value={String(note.id)} onChange={e=>setSelected(e.target.value)}>{notes.map(n=><option key={String(n.id)} value={n.id}>{n.titulo||'Sem título'}</option>)}</select><section style={card}><strong>Tamanho do cartão</strong><p style={{fontSize:12,opacity:.65}}>O aplicativo original possuía Normal, Largo e Grande. O valor fica preservado nos dados mesmo com a lista minimalista atual.</p><div style={{display:'flex',gap:6}}>{[['normal','Normal'],['largo','Largo'],['grande','Grande']].map(([value,label])=><button key={value} style={{...button,background:note.tamanho===value?'var(--bg-hover)':'var(--bg-card)'}} onClick={()=>size(value)}>{label}</button>)}</div></section></div>
}

function FinanceDetails({state,commit}:{state:MaiState;commit:Commit}){
 const finance=state.finance||{};const transactions=rows(finance.transactions);const categories=rows(finance.categories);const accounts=rows(finance.accounts);const cards=rows(finance.cards);const saved=(state.configs.financeFilters||{}) as Row
 const [order,setOrder]=useState(String(saved.order||'date_desc'));const [status,setStatus]=useState(String(saved.status||''));const [category,setCategory]=useState(String(saved.category||''));const [origin,setOrigin]=useState(String(saved.origin||''));const [paymentTx,setPaymentTx]=useState('')
 function persist(next:Row){commit(current=>({...current,configs:{...current.configs,financeFilters:{order,status,category,origin,...next}}}))}
 function change(field:string,value:string){if(field==='order')setOrder(value);if(field==='status')setStatus(value);if(field==='category')setCategory(value);if(field==='origin')setOrigin(value);persist({[field]:value})}
 const today=new Date().toISOString().slice(0,10);const filtered=transactions.filter(t=>{if(status==='pago'&&t.status!=='pago')return false;if(status==='pendente'&&t.status==='pago')return false;if(status==='atrasado'&&(t.status==='pago'||String(t.data||'')>=today))return false;if(category&&String(t.categoria||'')!==category)return false;if(origin&&String(t.conta_id||'')!==origin)return false;return true}).sort((a,b)=>order==='date_asc'?String(a.data).localeCompare(String(b.data)):order==='value_desc'?Number(b.valor||0)-Number(a.valor||0):order==='value_asc'?Number(a.valor||0)-Number(b.valor||0):order==='type'?String(a.tipo).localeCompare(String(b.tipo)):String(b.data).localeCompare(String(a.data)))
 const selected=transactions.find(t=>String(t.id)===paymentTx)
 function removePayment(index:number){if(!selected)return;const payments=rows(selected.pagamentos).filter((_,i)=>i!==index);const paid=payments.reduce((sum,p)=>sum+Number(p.valor||0),0);commit(current=>({...current,finance:{...current.finance,transactions:rows(current.finance.transactions).map(t=>String(t.id)===String(selected.id)?{...t,pagamentos:payments,valor_pago:paid,status:paid>=Number(t.valor||0)?'pago':paid>0?'parcial':'pendente'}:t)}}))}
 return <div style={{display:'grid',gap:12}}><section style={card}><strong>Organizar lançamentos</strong><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:7,marginTop:8}}><select style={input} value={order} onChange={e=>change('order',e.target.value)}><option value="date_desc">Data · mais recente</option><option value="date_asc">Data · mais antiga</option><option value="value_desc">Valor · maior</option><option value="value_asc">Valor · menor</option><option value="type">Tipo</option></select><select style={input} value={status} onChange={e=>change('status',e.target.value)}><option value="">Todos os status</option><option value="pago">Pago</option><option value="pendente">Pendente</option><option value="atrasado">Atrasado</option></select><select style={input} value={category} onChange={e=>change('category',e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={String(c.id)} value={c.nome}>{c.nome}</option>)}</select><select style={input} value={origin} onChange={e=>change('origin',e.target.value)}><option value="">Todas as origens</option>{accounts.map(a=><option key={String(a.id)} value={a.id}>{a.nome}</option>)}{cards.map(c=><option key={String(c.id)} value={`card|${c.id}`}>{c.nome}</option>)}</select></div><div style={{display:'grid',gap:5,marginTop:10,maxHeight:300,overflow:'auto'}}>{filtered.map(t=><button key={String(t.id)} style={{...button,textAlign:'left',display:'grid',gridTemplateColumns:'1fr auto'}} onClick={()=>setPaymentTx(String(t.id))}><span><b>{t.titulo}</b><small style={{display:'block',opacity:.58}}>{t.data} · {t.status||'pendente'} · {t.categoria||'Sem categoria'}</small></span><b>{t.tipo==='receita'?'+':'−'} {money.format(Number(t.valor||0))}</b></button>)}</div></section>{selected&&<section style={card}><strong>Pagamentos parciais · {selected.titulo}</strong><div style={{display:'grid',gap:6,marginTop:8}}>{rows(selected.pagamentos).map((p,index)=><div key={String(p.id||index)} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:7,alignItems:'center'}}><span>{p.data||'Sem data'}</span><b>{money.format(Number(p.valor||0))}</b><button style={button} onClick={()=>removePayment(index)}>Remover</button></div>)}{!rows(selected.pagamentos).length&&<small style={{opacity:.6}}>Nenhum pagamento parcial registrado.</small>}</div></section>}</div>
}

export function ModuleDetailParity(props:Props){
 if(!['habits','goals','notes','finance'].includes(props.view))return null
 const [open,setOpen]=useState(false);const label=props.view==='habits'?'Detalhes de Rotinas':props.view==='goals'?'Editor completo de Metas':props.view==='notes'?'Detalhes de Notas':'Organizador financeiro'
 return <><button onClick={()=>setOpen(true)} style={{position:'fixed',right:22,bottom:76,zIndex:8008,...button,fontWeight:700}}>{label}</button>{open&&<div style={overlay} onMouseDown={()=>setOpen(false)}><section style={sheet} onMouseDown={e=>e.stopPropagation()}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><h2 style={{margin:0}}>{label}</h2><button style={button} onClick={()=>setOpen(false)}>Fechar</button></header>{props.view==='habits'&&<HabitDetails state={props.state} commit={props.commit}/>} {props.view==='goals'&&<GoalDetails state={props.state} commit={props.commit} googleRpc={props.googleRpc}/>} {props.view==='notes'&&<NoteDetails state={props.state} commit={props.commit}/>} {props.view==='finance'&&<FinanceDetails state={props.state} commit={props.commit}/>}</section></div>}</>
}
